#!/usr/bin/env python3
"""Generates match programs of increasing complexity for tools/bench/run.sh.

Each family varies one thing that the decision tree is supposed to exploit:

  literals  k literal rows under the same constructor, plus a bind and a none row
  nested    k rows matching a constructor nested inside the same constructor
  columns   a full (m+1) x (m+1) matrix over a pair of options

The entry signature is fixed per family, so one bench driver in
tools/bench/drivers/ fits every size.
"""

import argparse
import pathlib

HEADER = "// generated by tools/bench/gen.py: {desc}\n"


def arm(body, bindings=""):
    return f"    case{bindings} {{\n{body}    }}\n"


def program(desc, scrutinee, rows, arms):
    patterns = ", ".join(rows)
    body = "".join(arms)
    return (
        HEADER.format(desc=desc)
        + "func.func @classify(%v: "
        + scrutinee
        + ") -> i32 {\n"
        + "  %c0 = arith.constant 0 : i32\n"
        + "  %c2 = arith.constant 2 : i32\n"
        + "  %r = match.match {patterns = ["
        + patterns
        + "]} %v : "
        + scrutinee
        + " -> i32\n"
        + body
        + "    default {\n      match.yield %c0 : i32\n    }\n"
        + "  return %r : i32\n}\n"
    )


def literals(k):
    rows = [f'#match.pattern<"some"(#match.pattern<"literal", {j} : i32>)>' for j in range(k)]
    rows += ['#match.pattern<"some"(#match.pattern<"bind">)>', '#match.pattern<"none">']
    arms = [arm(f"      %y{j} = arith.constant {j + 1} : i32\n      match.yield %y{j} : i32\n")
            for j in range(k)]
    arms.append(arm("      %twice = arith.muli %x, %c2 : i32\n      match.yield %twice : i32\n",
                    " (%x: i32)"))
    arms.append(arm("      match.yield %c0 : i32\n"))
    return program(f"{k} literal rows under some", "!match.option<i32>", rows, arms)


def nested(k):
    inner = "!match.option<i32>"
    rows = [f'#match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", {j} : i32>)>)>' for j in range(k)]
    rows += ['#match.pattern<"some"(#match.pattern<"none">)>',
             '#match.pattern<"some"(#match.pattern<"bind">)>',
             '#match.pattern<"none">']
    arms = [arm(f"      %y{j} = arith.constant {j + 1} : i32\n      match.yield %y{j} : i32\n")
            for j in range(k)]
    arms.append(arm("      %one = arith.constant 1 : i32\n      match.yield %one : i32\n"))
    arms.append(arm("      match.yield %c0 : i32\n", f" (%w: {inner})"))
    arms.append(arm("      match.yield %c0 : i32\n"))
    return program(f"{k} rows over a nested constructor",
                   f"!match.option<{inner}>", rows, arms)


def columns(m):
    opt = "!match.option<i32>"
    lefts = [f'#match.pattern<"some"(#match.pattern<"literal", {j} : i32>)>' for j in range(m)]
    lefts.append('#match.pattern<"none">')
    rights = [f'#match.pattern<"some"(#match.pattern<"literal", {j} : i32>)>' for j in range(m)]
    rights.append('#match.pattern<"none">')
    rows = [f'#match.pattern<"pair"({l}, {r})>' for l in lefts for r in rights]
    arms = []
    for i, _ in enumerate(rows):
        arms.append(arm(f"      %y{i} = arith.constant {i + 1} : i32\n      match.yield %y{i} : i32\n"))
    return program(f"{len(rows)}-row matrix over two option columns",
                   f"!match.pair<{opt}, {opt}>", rows, arms)


FAMILIES = {
    "literals": (literals, [2, 4, 8, 16]),
    "nested": (nested, [2, 4, 8]),
    "columns": (columns, [1, 2, 3]),
}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--outdir", default="build/bench")
    parser.add_argument("--family", choices=sorted(FAMILIES))
    args = parser.parse_args()

    outdir = pathlib.Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    for name, (build, sizes) in FAMILIES.items():
        if args.family and name != args.family:
            continue
        for size in sizes:
            path = outdir / f"{name}-{size}.mlir"
            path.write_text(build(size))
            print(f"{path}\t{name}")


if __name__ == "__main__":
    main()
