// generated by tools/gen_programs.py: 4 literal rows under some
func.func @classify(%v: !match.option<i32>) -> i32 {
  %c0 = arith.constant 0 : i32
  %c2 = arith.constant 2 : i32
  %r = match.match {patterns = [#match.pattern<"some"(#match.pattern<"literal", 0 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 1 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 2 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 3 : i32>)>, #match.pattern<"some"(#match.pattern<"bind">)>, #match.pattern<"none">]} %v : !match.option<i32> -> i32
    case {
      %y0 = arith.constant 1 : i32
      match.yield %y0 : i32
    }
    case {
      %y1 = arith.constant 2 : i32
      match.yield %y1 : i32
    }
    case {
      %y2 = arith.constant 3 : i32
      match.yield %y2 : i32
    }
    case {
      %y3 = arith.constant 4 : i32
      match.yield %y3 : i32
    }
    case (%x: i32) {
      %twice = arith.muli %x, %c2 : i32
      match.yield %twice : i32
    }
    case {
      match.yield %c0 : i32
    }
    default {
      match.yield %c0 : i32
    }
  return %r : i32
}
