// generated by tools/gen_programs.py: 16 literal rows under some
func.func @classify(%v: !match.option<i32>) -> i32 {
  %c0 = arith.constant 0 : i32
  %c2 = arith.constant 2 : i32
  %r = match.match {patterns = [#match.pattern<"some"(#match.pattern<"literal", 0 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 1 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 2 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 3 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 4 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 5 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 6 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 7 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 8 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 9 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 10 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 11 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 12 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 13 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 14 : i32>)>, #match.pattern<"some"(#match.pattern<"literal", 15 : i32>)>, #match.pattern<"some"(#match.pattern<"bind">)>, #match.pattern<"none">]} %v : !match.option<i32> -> i32
    case {
      %y0 = arith.constant 1 : i32
      match.yield %y0 : i32
    }
    case {
      %y1 = arith.constant 2 : i32
      match.yield %y1 : i32
    }
    case {
      %y2 = arith.constant 3 : i32
      match.yield %y2 : i32
    }
    case {
      %y3 = arith.constant 4 : i32
      match.yield %y3 : i32
    }
    case {
      %y4 = arith.constant 5 : i32
      match.yield %y4 : i32
    }
    case {
      %y5 = arith.constant 6 : i32
      match.yield %y5 : i32
    }
    case {
      %y6 = arith.constant 7 : i32
      match.yield %y6 : i32
    }
    case {
      %y7 = arith.constant 8 : i32
      match.yield %y7 : i32
    }
    case {
      %y8 = arith.constant 9 : i32
      match.yield %y8 : i32
    }
    case {
      %y9 = arith.constant 10 : i32
      match.yield %y9 : i32
    }
    case {
      %y10 = arith.constant 11 : i32
      match.yield %y10 : i32
    }
    case {
      %y11 = arith.constant 12 : i32
      match.yield %y11 : i32
    }
    case {
      %y12 = arith.constant 13 : i32
      match.yield %y12 : i32
    }
    case {
      %y13 = arith.constant 14 : i32
      match.yield %y13 : i32
    }
    case {
      %y14 = arith.constant 15 : i32
      match.yield %y14 : i32
    }
    case {
      %y15 = arith.constant 16 : i32
      match.yield %y15 : i32
    }
    case (%x: i32) {
      %twice = arith.muli %x, %c2 : i32
      match.yield %twice : i32
    }
    case {
      match.yield %c0 : i32
    }
    default {
      match.yield %c0 : i32
    }
  return %r : i32
}
