// generated by tools/gen_programs.py: 8 rows over a nested constructor
func.func @classify(%v: !match.option<!match.option<i32>>) -> i32 {
  %c0 = arith.constant 0 : i32
  %c2 = arith.constant 2 : i32
  %r = match.match {patterns = [#match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 0 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 1 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 2 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 3 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 4 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 5 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 6 : i32>)>)>, #match.pattern<"some"(#match.pattern<"some"(#match.pattern<"literal", 7 : i32>)>)>, #match.pattern<"some"(#match.pattern<"none">)>, #match.pattern<"some"(#match.pattern<"bind">)>, #match.pattern<"none">]} %v : !match.option<!match.option<i32>> -> i32
    case {
      %y0 = arith.constant 1 : i32
      match.yield %y0 : i32
    }
    case {
      %y1 = arith.constant 2 : i32
      match.yield %y1 : i32
    }
    case {
      %y2 = arith.constant 3 : i32
      match.yield %y2 : i32
    }
    case {
      %y3 = arith.constant 4 : i32
      match.yield %y3 : i32
    }
    case {
      %y4 = arith.constant 5 : i32
      match.yield %y4 : i32
    }
    case {
      %y5 = arith.constant 6 : i32
      match.yield %y5 : i32
    }
    case {
      %y6 = arith.constant 7 : i32
      match.yield %y6 : i32
    }
    case {
      %y7 = arith.constant 8 : i32
      match.yield %y7 : i32
    }
    case {
      %one = arith.constant 1 : i32
      match.yield %one : i32
    }
    case (%w: !match.option<i32>) {
      match.yield %c0 : i32
    }
    case {
      match.yield %c0 : i32
    }
    default {
      match.yield %c0 : i32
    }
  return %r : i32
}
